/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TestSiteApplication {
    id: string;
    propertyType: PropertyType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    energySources: Array<EnergySource>;
    phone?: string;
    location: string;
}
export interface PartnershipInquiry {
    id: string;
    partnershipType: PartnershipType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    organization?: string;
}
export type Time = bigint;
export interface InvestorInquiry {
    id: string;
    name: string;
    email: string;
    company?: string;
    message: string;
    timestamp: Time;
    investmentRange: InvestmentRange;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface GeneralInquiry {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export enum EnergySource {
    both = "both",
    wind = "wind",
    waterStream = "waterStream"
}
export enum InvestmentRange {
    over250k = "over250k",
    range_10k_50k = "range_10k_50k",
    under10k = "under10k",
    range_50k_250k = "range_50k_250k"
}
export enum PartnershipType {
    media = "media",
    other = "other",
    research = "research",
    technology = "technology",
    distribution = "distribution"
}
export enum PropertyType {
    commercial = "commercial",
    other = "other",
    farmAgricultural = "farmAgricultural",
    residential = "residential",
    industrial = "industrial",
    remoteOffGrid = "remoteOffGrid"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    adminClearAllData(): Promise<void>;
    adminDeleteEntry(entryType: string, id: string): Promise<boolean>;
    getAllInquiries(): Promise<{
        investors: Array<InvestorInquiry>;
        testSites: Array<TestSiteApplication>;
        partners: Array<PartnershipInquiry>;
        general: Array<GeneralInquiry>;
    }>;
    getGeneralInquiries(): Promise<Array<GeneralInquiry>>;
    getInvestorInquiries(): Promise<Array<InvestorInquiry>>;
    getPartnershipInquiries(): Promise<Array<PartnershipInquiry>>;
    getTestSiteApplications(): Promise<Array<TestSiteApplication>>;
    submitGeneralInquiry(name: string, email: string, message: string): Promise<string>;
    submitInvestorInquiry(name: string, email: string, company: string | null, investmentRange: InvestmentRange, message: string): Promise<string>;
    submitPartnershipInquiry(name: string, email: string, organization: string | null, partnershipType: PartnershipType, message: string): Promise<string>;
    submitTestSiteApplication(name: string, email: string, phone: string | null, location: string, propertyType: PropertyType, energySources: Array<EnergySource>, message: string): Promise<string>;
}
import type { EnergySource as _EnergySource, GeneralInquiry as _GeneralInquiry, InvestmentRange as _InvestmentRange, InvestorInquiry as _InvestorInquiry, PartnershipInquiry as _PartnershipInquiry, PartnershipType as _PartnershipType, PropertyType as _PropertyType, TestSiteApplication as _TestSiteApplication, Time as _Time, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminClearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminClearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminClearAllData();
            return result;
        }
    }
    async adminDeleteEntry(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteEntry(arg0, arg1);
            return result;
        }
    }
    async getAllInquiries(): Promise<{
        investors: Array<InvestorInquiry>;
        testSites: Array<TestSiteApplication>;
        partners: Array<PartnershipInquiry>;
        general: Array<GeneralInquiry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGeneralInquiries(): Promise<Array<GeneralInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeneralInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeneralInquiries();
            return result;
        }
    }
    async getInvestorInquiries(): Promise<Array<InvestorInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestorInquiries();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestorInquiries();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnershipInquiries(): Promise<Array<PartnershipInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnershipInquiries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnershipInquiries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestSiteApplications(): Promise<Array<TestSiteApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestSiteApplications();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestSiteApplications();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitGeneralInquiry(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGeneralInquiry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGeneralInquiry(arg0, arg1, arg2);
            return result;
        }
    }
    async submitInvestorInquiry(arg0: string, arg1: string, arg2: string | null, arg3: InvestmentRange, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInvestorInquiry(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_InvestmentRange_n29(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInvestorInquiry(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_InvestmentRange_n29(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async submitPartnershipInquiry(arg0: string, arg1: string, arg2: string | null, arg3: PartnershipType, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPartnershipInquiry(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_PartnershipType_n31(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPartnershipInquiry(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_PartnershipType_n31(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async submitTestSiteApplication(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: PropertyType, arg5: Array<EnergySource>, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestSiteApplication(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PropertyType_n33(this._uploadFile, this._downloadFile, arg4), to_candid_vec_n35(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestSiteApplication(arg0, arg1, to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PropertyType_n33(this._uploadFile, this._downloadFile, arg4), to_candid_vec_n35(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
}
function from_candid_EnergySource_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnergySource): EnergySource {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentRange_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentRange): InvestmentRange {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_InvestorInquiry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestorInquiry): InvestorInquiry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PartnershipInquiry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartnershipInquiry): PartnershipInquiry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PartnershipType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartnershipType): PartnershipType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TestSiteApplication_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestSiteApplication): TestSiteApplication {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    email: string;
    company: [] | [string];
    message: string;
    timestamp: _Time;
    investmentRange: _InvestmentRange;
}): {
    id: string;
    name: string;
    email: string;
    company?: string;
    message: string;
    timestamp: Time;
    investmentRange: InvestmentRange;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        company: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.company)),
        message: value.message,
        timestamp: value.timestamp,
        investmentRange: from_candid_InvestmentRange_n13(_uploadFile, _downloadFile, value.investmentRange)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    propertyType: _PropertyType;
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    energySources: Array<_EnergySource>;
    phone: [] | [string];
    location: string;
}): {
    id: string;
    propertyType: PropertyType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    energySources: Array<EnergySource>;
    phone?: string;
    location: string;
} {
    return {
        id: value.id,
        propertyType: from_candid_PropertyType_n18(_uploadFile, _downloadFile, value.propertyType),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        energySources: from_candid_vec_n20(_uploadFile, _downloadFile, value.energySources),
        phone: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.phone)),
        location: value.location
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    partnershipType: _PartnershipType;
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    organization: [] | [string];
}): {
    id: string;
    partnershipType: PartnershipType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    organization?: string;
} {
    return {
        id: value.id,
        partnershipType: from_candid_PartnershipType_n26(_uploadFile, _downloadFile, value.partnershipType),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        organization: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.organization))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    investors: Array<_InvestorInquiry>;
    testSites: Array<_TestSiteApplication>;
    partners: Array<_PartnershipInquiry>;
    general: Array<_GeneralInquiry>;
}): {
    investors: Array<InvestorInquiry>;
    testSites: Array<TestSiteApplication>;
    partners: Array<PartnershipInquiry>;
    general: Array<GeneralInquiry>;
} {
    return {
        investors: from_candid_vec_n9(_uploadFile, _downloadFile, value.investors),
        testSites: from_candid_vec_n15(_uploadFile, _downloadFile, value.testSites),
        partners: from_candid_vec_n23(_uploadFile, _downloadFile, value.partners),
        general: value.general
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    over250k: null;
} | {
    range_10k_50k: null;
} | {
    under10k: null;
} | {
    range_50k_250k: null;
}): InvestmentRange {
    return "over250k" in value ? InvestmentRange.over250k : "range_10k_50k" in value ? InvestmentRange.range_10k_50k : "under10k" in value ? InvestmentRange.under10k : "range_50k_250k" in value ? InvestmentRange.range_50k_250k : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    other: null;
} | {
    farmAgricultural: null;
} | {
    residential: null;
} | {
    industrial: null;
} | {
    remoteOffGrid: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "other" in value ? PropertyType.other : "farmAgricultural" in value ? PropertyType.farmAgricultural : "residential" in value ? PropertyType.residential : "industrial" in value ? PropertyType.industrial : "remoteOffGrid" in value ? PropertyType.remoteOffGrid : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    wind: null;
} | {
    waterStream: null;
}): EnergySource {
    return "both" in value ? EnergySource.both : "wind" in value ? EnergySource.wind : "waterStream" in value ? EnergySource.waterStream : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media: null;
} | {
    other: null;
} | {
    research: null;
} | {
    technology: null;
} | {
    distribution: null;
}): PartnershipType {
    return "media" in value ? PartnershipType.media : "other" in value ? PartnershipType.other : "research" in value ? PartnershipType.research : "technology" in value ? PartnershipType.technology : "distribution" in value ? PartnershipType.distribution : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestSiteApplication>): Array<TestSiteApplication> {
    return value.map((x)=>from_candid_TestSiteApplication_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EnergySource>): Array<EnergySource> {
    return value.map((x)=>from_candid_EnergySource_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PartnershipInquiry>): Array<PartnershipInquiry> {
    return value.map((x)=>from_candid_PartnershipInquiry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvestorInquiry>): Array<InvestorInquiry> {
    return value.map((x)=>from_candid_InvestorInquiry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_EnergySource_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergySource): _EnergySource {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_InvestmentRange_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentRange): _InvestmentRange {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_PartnershipType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartnershipType): _PartnershipType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvestmentRange): {
    over250k: null;
} | {
    range_10k_50k: null;
} | {
    under10k: null;
} | {
    range_50k_250k: null;
} {
    return value == InvestmentRange.over250k ? {
        over250k: null
    } : value == InvestmentRange.range_10k_50k ? {
        range_10k_50k: null
    } : value == InvestmentRange.under10k ? {
        under10k: null
    } : value == InvestmentRange.range_50k_250k ? {
        range_50k_250k: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartnershipType): {
    media: null;
} | {
    other: null;
} | {
    research: null;
} | {
    technology: null;
} | {
    distribution: null;
} {
    return value == PartnershipType.media ? {
        media: null
    } : value == PartnershipType.other ? {
        other: null
    } : value == PartnershipType.research ? {
        research: null
    } : value == PartnershipType.technology ? {
        technology: null
    } : value == PartnershipType.distribution ? {
        distribution: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    other: null;
} | {
    farmAgricultural: null;
} | {
    residential: null;
} | {
    industrial: null;
} | {
    remoteOffGrid: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.other ? {
        other: null
    } : value == PropertyType.farmAgricultural ? {
        farmAgricultural: null
    } : value == PropertyType.residential ? {
        residential: null
    } : value == PropertyType.industrial ? {
        industrial: null
    } : value == PropertyType.remoteOffGrid ? {
        remoteOffGrid: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergySource): {
    both: null;
} | {
    wind: null;
} | {
    waterStream: null;
} {
    return value == EnergySource.both ? {
        both: null
    } : value == EnergySource.wind ? {
        wind: null
    } : value == EnergySource.waterStream ? {
        waterStream: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EnergySource>): Array<_EnergySource> {
    return value.map((x)=>to_candid_EnergySource_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
