/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const InvestmentRange = IDL.Variant({
  'over250k' : IDL.Null,
  'range_10k_50k' : IDL.Null,
  'under10k' : IDL.Null,
  'range_50k_250k' : IDL.Null,
});
export const InvestorInquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'investmentRange' : InvestmentRange,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'other' : IDL.Null,
  'farmAgricultural' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
  'remoteOffGrid' : IDL.Null,
});
export const EnergySource = IDL.Variant({
  'both' : IDL.Null,
  'wind' : IDL.Null,
  'waterStream' : IDL.Null,
});
export const TestSiteApplication = IDL.Record({
  'id' : IDL.Text,
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'energySources' : IDL.Vec(EnergySource),
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const PartnershipType = IDL.Variant({
  'media' : IDL.Null,
  'other' : IDL.Null,
  'research' : IDL.Null,
  'technology' : IDL.Null,
  'distribution' : IDL.Null,
});
export const PartnershipInquiry = IDL.Record({
  'id' : IDL.Text,
  'partnershipType' : PartnershipType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'organization' : IDL.Opt(IDL.Text),
});
export const GeneralInquiry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminClearAllData' : IDL.Func([], [], []),
  'adminDeleteEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllInquiries' : IDL.Func(
      [],
      [
        IDL.Record({
          'investors' : IDL.Vec(InvestorInquiry),
          'testSites' : IDL.Vec(TestSiteApplication),
          'partners' : IDL.Vec(PartnershipInquiry),
          'general' : IDL.Vec(GeneralInquiry),
        }),
      ],
      ['query'],
    ),
  'getGeneralInquiries' : IDL.Func([], [IDL.Vec(GeneralInquiry)], ['query']),
  'getInvestorInquiries' : IDL.Func([], [IDL.Vec(InvestorInquiry)], ['query']),
  'getPartnershipInquiries' : IDL.Func(
      [],
      [IDL.Vec(PartnershipInquiry)],
      ['query'],
    ),
  'getTestSiteApplications' : IDL.Func(
      [],
      [IDL.Vec(TestSiteApplication)],
      ['query'],
    ),
  'submitGeneralInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitInvestorInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), InvestmentRange, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitPartnershipInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), PartnershipType, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitTestSiteApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        PropertyType,
        IDL.Vec(EnergySource),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const InvestmentRange = IDL.Variant({
    'over250k' : IDL.Null,
    'range_10k_50k' : IDL.Null,
    'under10k' : IDL.Null,
    'range_50k_250k' : IDL.Null,
  });
  const InvestorInquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'investmentRange' : InvestmentRange,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'other' : IDL.Null,
    'farmAgricultural' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
    'remoteOffGrid' : IDL.Null,
  });
  const EnergySource = IDL.Variant({
    'both' : IDL.Null,
    'wind' : IDL.Null,
    'waterStream' : IDL.Null,
  });
  const TestSiteApplication = IDL.Record({
    'id' : IDL.Text,
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'energySources' : IDL.Vec(EnergySource),
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const PartnershipType = IDL.Variant({
    'media' : IDL.Null,
    'other' : IDL.Null,
    'research' : IDL.Null,
    'technology' : IDL.Null,
    'distribution' : IDL.Null,
  });
  const PartnershipInquiry = IDL.Record({
    'id' : IDL.Text,
    'partnershipType' : PartnershipType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'organization' : IDL.Opt(IDL.Text),
  });
  const GeneralInquiry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminClearAllData' : IDL.Func([], [], []),
    'adminDeleteEntry' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllInquiries' : IDL.Func(
        [],
        [
          IDL.Record({
            'investors' : IDL.Vec(InvestorInquiry),
            'testSites' : IDL.Vec(TestSiteApplication),
            'partners' : IDL.Vec(PartnershipInquiry),
            'general' : IDL.Vec(GeneralInquiry),
          }),
        ],
        ['query'],
      ),
    'getGeneralInquiries' : IDL.Func([], [IDL.Vec(GeneralInquiry)], ['query']),
    'getInvestorInquiries' : IDL.Func(
        [],
        [IDL.Vec(InvestorInquiry)],
        ['query'],
      ),
    'getPartnershipInquiries' : IDL.Func(
        [],
        [IDL.Vec(PartnershipInquiry)],
        ['query'],
      ),
    'getTestSiteApplications' : IDL.Func(
        [],
        [IDL.Vec(TestSiteApplication)],
        ['query'],
      ),
    'submitGeneralInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitInvestorInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), InvestmentRange, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitPartnershipInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), PartnershipType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitTestSiteApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          PropertyType,
          IDL.Vec(EnergySource),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };