/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EnergySource = { 'both' : null } |
  { 'wind' : null } |
  { 'waterStream' : null };
export interface GeneralInquiry {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type InvestmentRange = { 'over250k' : null } |
  { 'range_10k_50k' : null } |
  { 'under10k' : null } |
  { 'range_50k_250k' : null };
export interface InvestorInquiry {
  'id' : string,
  'name' : string,
  'email' : string,
  'company' : [] | [string],
  'message' : string,
  'timestamp' : Time,
  'investmentRange' : InvestmentRange,
}
export interface PartnershipInquiry {
  'id' : string,
  'partnershipType' : PartnershipType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'organization' : [] | [string],
}
export type PartnershipType = { 'media' : null } |
  { 'other' : null } |
  { 'research' : null } |
  { 'technology' : null } |
  { 'distribution' : null };
export type PropertyType = { 'commercial' : null } |
  { 'other' : null } |
  { 'farmAgricultural' : null } |
  { 'residential' : null } |
  { 'industrial' : null } |
  { 'remoteOffGrid' : null };
export interface TestSiteApplication {
  'id' : string,
  'propertyType' : PropertyType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'energySources' : Array<EnergySource>,
  'phone' : [] | [string],
  'location' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminClearAllData' : ActorMethod<[], undefined>,
  'adminDeleteEntry' : ActorMethod<[string, string], boolean>,
  'getAllInquiries' : ActorMethod<
    [],
    {
      'investors' : Array<InvestorInquiry>,
      'testSites' : Array<TestSiteApplication>,
      'partners' : Array<PartnershipInquiry>,
      'general' : Array<GeneralInquiry>,
    }
  >,
  'getGeneralInquiries' : ActorMethod<[], Array<GeneralInquiry>>,
  'getInvestorInquiries' : ActorMethod<[], Array<InvestorInquiry>>,
  'getPartnershipInquiries' : ActorMethod<[], Array<PartnershipInquiry>>,
  'getTestSiteApplications' : ActorMethod<[], Array<TestSiteApplication>>,
  'submitGeneralInquiry' : ActorMethod<[string, string, string], string>,
  'submitInvestorInquiry' : ActorMethod<
    [string, string, [] | [string], InvestmentRange, string],
    string
  >,
  'submitPartnershipInquiry' : ActorMethod<
    [string, string, [] | [string], PartnershipType, string],
    string
  >,
  'submitTestSiteApplication' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      PropertyType,
      Array<EnergySource>,
      string,
    ],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];